name: Daily Price Fetcher

on:
    schedule: [{cron: "0 1 * * *"}]
    workflow_dispatch:
      inputs:
        DATE:
          description: The date to fetch prices for, format `YYYY-MM-DD`.
          required: false
          type: string

jobs:
  fetch-prices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: yarn install

      - name: Run price fetcher
        run: yarn start
        env:
          DATE: ${{ github.event.inputs.DATE }}

      - name: Get today's date_time
        id: today_date_time
        run: echo "date_time=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - uses: stefanzweifel/git-auto-commit-action@v5
        ## if DATE is set, use it as the commit message, otherwise use today's date
        with:
          commit_message: "update for ${{ github.event.inputs.DATE || steps.today_date_time.outputs.date_time }}"
